<?php
/**
 * Created by PhpStorm.
 * User: victor
 * Date: 17/02/2018
 * Time: 12:13 PM
 */
namespace v1\Controller;

use v1\Model\IpsModel;
use v1\Model\PortRangesModel;
use v1\Model\PortsModel;

class OperatorController extends BaseController
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        if ($this->user_info['type'] != 'ADMIN')
        {
            $this->error('Access Denied','/',3);
        }
    }

    public function managePorts()
    {
        $Ips = new IpsModel();
        $PortRanges = new PortRangesModel();

        $this->assign('ips',$Ips->order('id desc')->select());
        $this->assign('port_ranges',$PortRanges->where('status != "DELETED"')->order('id desc')->select());
        $this->assign('SideBar_Selected','Admin_Ports');
        $this->meta_title = '管理员::端口Range';
        $this->display();
    }

    public function applies()
    {
        $this->assign('SideBar_Selected','Admin_Applies');
        $this->meta_title = '管理员::审核';
        $this->display();
    }

    public function siteConfig()
    {
        $this->assign('SideBar_Selected','Admin_SiteConfig');
        $this->meta_title = '管理员::站点配置';
        $this->display();
    }

    public function Action_port_range_create()
    {
        $ip_id = I('post.ip_id');
        $start_port = I('post.start_port');
        $end_port = I('post.end_port');
        $range_id = (new PortRangesModel())->data(array("ip_id"=>$ip_id,"start_port"=>$start_port,"end_port"=>$end_port,"operator_id"=>getUID()))->add();
        $Ports = new PortsModel();
        for ($i=0;$i<=$end_port-$start_port;$i++)
        {
            $Ports->data(array(
                "port" => $start_port+$i,
                "ip_id" => $ip_id,
                "range_id" => $range_id,
                "create_at" => getDateTime(),
                "status" => "NORMAL",
                "apply_status" => "UNUSED",
            ))->add();
        }
        echo json_encode(array(
            "success" => true,
            "msg" => "已经成功添加端口Range",
        ));
    }

    public function Action_port_range_delete()
    {
        $id = I('post.id');
        (new PortRangesModel())->where(array("id"=>$id))->data(array("status"=>"DELETED"))->save();
        (new PortsModel())->where(array("range_id"=>$id))->data(array("status"=>"CANCELLED"))->save();
        echo json_encode(array(
            "success" => true,
            "msg" => "已经成功删除,id=".$id.',关联端口状态已调整为CANCELLED',
        ));

        //TODO:删除后还需执行删除转发操作
    }
}