<?php
/**
 * Created by PhpStorm.
 * User: victor
 * Date: 17/02/2018
 * Time: 12:13 PM
 */
namespace v1\Controller;

use v1\Model\PortRangesModel;

class OperatorController extends BaseController
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        if ($this->user_info['type'] != 'ADMIN')
        {
            $this->error('Access Denied','/',3);
        }
    }

    public function managePorts()
    {
        $PortRanges = new PortRangesModel();

        $this->assign('port_ranges',$PortRanges->order('id desc')->select());
        $this->assign('SideBar_Selected','Admin_Ports');
        $this->meta_title = '管理员::端口Range';
        $this->display();
    }

    public function applies()
    {
        $this->assign('SideBar_Selected','Admin_Applies');
        $this->meta_title = '管理员::审核';
        $this->display();
    }

    public function siteConfig()
    {
        $this->assign('SideBar_Selected','Admin_SiteConfig');
        $this->meta_title = '管理员::站点配置';
        $this->display();
    }
}