<?php
// +----------------------------------------------------------------------
// | Changjunese Scrore v2.0
// +----------------------------------------------------------------------
// | Copyright (c) 2015-2017 https://www.northme.com All rights reserved.
// +----------------------------------------------------------------------
// | Author: Victor.Chen <victor.chen@northme.com>
// +----------------------------------------------------------------------
// | Create at: 2017/10/17 23:12
// +----------------------------------------------------------------------
namespace Score\Controller;
class EmptyController extends BaseController{
    function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        exit('Controller doesn\'t exists.');
    }
}