<?php
// +----------------------------------------------------------------------
// | Changjunese Scrore v2.0
// +----------------------------------------------------------------------
// | Copyright (c) 2015-2017 https://www.northme.com All rights reserved.
// +----------------------------------------------------------------------
// | Author: Victor.Chen <victor.chen@northme.com>
// +----------------------------------------------------------------------
// | Create at: 2017/10/20 23:27
// +----------------------------------------------------------------------
namespace Score\Controller;
use Score\Model\QueryExamsModel;

class QueryController extends BaseController
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function _empty(){
        exit('未创建方法');
    }

    public function api(){
        $this->assign('SideBar_Selected','query_api');
        $this->meta_title = '查询API接口（未开放）';
        $this->display();
    }

    public function qrobot(){
        $this->assign('SideBar_Selected','query_qrobot');
        $this->meta_title = '群机器人申请（未开放）';
        $this->display();
    }

    public function routine()
    {
        $Exams = new QueryExamsModel();
        $exams_available = $Exams->getAvaliableExamsDetail();
        $this->assign('exams_available',$exams_available);
        $this->assign('SideBar_Selected', 'query_routine');
        $this->meta_title = '常规查询';
        $this->display();
    }

    public function Action_rtQuery()
    {
        $exam_id = I('post.exam_id');
        $stuno = I('post.stuno');
        $stuname = I('post.stuname');
        $Exam = new QueryExamsModel();
        $res = $Exam->getResultByStu($exam_id,$stuno,$stuname);
        if (!$res)
        {
            echo json_encode(array(
                "error" => true,
                "msg" => "我们无法在数据库中查找到您提交的信息。"
            ));
        } else {
            $thisallc = M('system')->where('name = "query-count"')->select()[0]['value'];
            M('system')->where('name = "query-count"')->data(array("value"=>$thisallc+1))->save();
            echo json_encode(array(
                "success" => true,
                "msg" => "查询成功，减少一个本月查询机会",
                "result" => $res,
                "resultHtmltable" => '<div class="panel panel-default" id="resDiv">
                        <div class="panel-heading">'.$stuname.'在这次考试中，成绩如下</div>'.
                    $this->sc2HtmlTable(unserialize($res)).'</div>',
            ));
        }
    }

    public function sc2HtmlTable($score)
    {
        $str ='';
        foreach ($score as $key =>$value)
        {
            $str2 ='';
            foreach ($value as $key2 =>$value2)
            {
                $str2 .= '<td>'.$value2.'</td>';
            }
            $str .= '<tr>
<td class="text-center">'.$key.'</td>'.$str2.'
</tr>';
        }
        $str = '<div class="table-responsive">
                            <table class="table table-striped b-t b-light">
                                <thead>
                                <tr>
                                    <th class="text-center">科目</th>
                                    <th>分数</th>
                                    <th>班名</th>
                                    <th>校名</th>
                                    <th>级名</th>
                                </tr>
                                </thead>
                                <tbody>
                                '.$str.'
                                </tbody>
                            </table>
                        </div>';
        return $str;
    }
}